### ISSUE TITLE
<Bitbucket:514> 初回起動時に ArgumentNullException で落ちる

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#514]
Hyper-V Windows 10 開発環境 で初回起動時に謎いエラーが発生する。  
ユーザーID取得時にへんてこりんなことになってるんだろうけど、なぜかが不明。

‌

```
---------------------------

---------------------------
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')

   at System.Text.Encoding.GetBytes(String s)

   at ContentTypeTextNet.Pe.Main.Models.Logic.UserIdManager.CreateFromEnvironment()

   at ContentTypeTextNet.Pe.Main.Models.Applications.ApplicationInitializer.Initialize(App app, StartupEventArgs e)

   at ContentTypeTextNet.Pe.Main.App.OnStartup(StartupEventArgs e)

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------
```

![](https://bitbucket.org/repo/7xyG8G/images/3049283289-image.png)
‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#514](https://bitbucket.org/sk_0520/pe/issues/514) |
| 起票日時 | `2020-02-25T19:52:10Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
![](https://bitbucket.org/repo/7xyG8G/images/4069603438-image.png)
![](https://bitbucket.org/repo/7xyG8G/images/2900931056-image.png)
とったどー！

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#514 コメント](https://bitbucket.org/sk_0520/pe/issues/514#comment-56303065) |
| コメント日時 | `2020-02-25T20:09:49Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #514


→ 《cset f41c1799c697》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#514 コメント](https://bitbucket.org/sk_0520/pe/issues/514#comment-56303160) |
| コメント日時 | `2020-02-25T20:17:36Z` |
| コメントユーザー | `sk_0520` |
