### ISSUE TITLE
<Bitbucket:532> 設定画面で落ちる

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#532]
再現手順は不明。

```
2020-02-27 11:13:36.134|ERROR| 17326|<1>| 1, 'System.Windows.Documents.Run' は、Visual または Visual3D ではありません。 System.InvalidOperationException: 'System.Windows.Documents.Run' は、Visual または Visual3D ではありません。
   at MS.Internal.Media.VisualTreeUtils.AsVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at ContentTypeTextNet.Pe.Core.Models.UIUtility.GetVisualClosest[T](DependencyObject depObj)
   at ContentTypeTextNet.Pe.Main.Views.ScrollTuner.View_PreviewMouseWheel(Object sender, MouseWheelEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#532](https://bitbucket.org/sk_0520/pe/issues/532) |
| 起票日時 | `2020-02-27T11:38:13Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
```
2020-02-27 11:38:29.763|ERROR|  9199|<1>| 1, 'System.Windows.Documents.Run' は、Visual または Visual3D ではありません。 System.InvalidOperationException: 'System.Windows.Documents.Run' は、Visual または Visual3D ではありません。
   at MS.Internal.Media.VisualTreeUtils.AsVisual(DependencyObject element, Visual& visual, Visual3D& visual3D)
   at System.Windows.Media.VisualTreeHelper.GetParent(DependencyObject reference)
   at ContentTypeTextNet.Pe.Core.Models.UIUtility.GetVisualClosest[T](DependencyObject depObj)
   at ContentTypeTextNet.Pe.Main.Views.ScrollTuner.View_PreviewMouseWheel(Object sender, MouseWheelEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.ContentElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#532 コメント](https://bitbucket.org/sk_0520/pe/issues/532#comment-56327991) |
| コメント日時 | `2020-02-27T11:39:24Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
![](https://bitbucket.org/repo/7xyG8G/images/2312805745-image.png)
赤枠でスクロールすると落ちる。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#532 コメント](https://bitbucket.org/sk_0520/pe/issues/532#comment-56328030) |
| コメント日時 | `2020-02-27T11:47:03Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #532


→ 《cset 140fdfe6e900》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#532 コメント](https://bitbucket.org/sk_0520/pe/issues/532#comment-56328106) |
| コメント日時 | `2020-02-27T11:57:58Z` |
| コメントユーザー | `sk_0520` |
