### ISSUE TITLE
<Bitbucket:534> ネットワークドライブのコードが取得できない

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#534]
0\.83.0 変換時になんか変になあるっぽい。

変換はまぁともかく、通常使用でもなるはずなので調査が必要。

---

```
Software: Pe
Version: 0.86.000-81d553bb209cb33694013c0c3fb3c36796975d1b
BuildType: Release
Process: 64
Platform: 64
OS: Microsoft Windows NT 10.0.18363.0
CLR: v4.0.30319
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#534](https://bitbucket.org/sk_0520/pe/issues/534) |
| 起票日時 | `2020-02-27T14:22:42Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
コンテキストメニューから親ディレクトリをコピーすると落ちる模様。

ログもらった。

‌

```
2020-02-27 14:23:39.098|ERROR|  2624|<1>| 1, Value cannot be null. (Parameter 'textData') System.ArgumentNullException: Value cannot be null. (Parameter 'textData')
   at System.Windows.DataObject.SetText(String textData, TextDataFormat format)
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherItem.LauncherItemElement.CopyParentDirectory()
   at ContentTypeTextNet.Pe.Main.ViewModels.LauncherItem.LauncherFileViewModel.<get_CopyParentDirectoryCommand>b__29_1()
   at Prism.Commands.DelegateCommand.Execute()
   at Prism.Commands.DelegateCommand.Execute(Object parameter)
   at Prism.Commands.DelegateCommandBase.System.Windows.Input.ICommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#534 コメント](https://bitbucket.org/sk_0520/pe/issues/534#comment-56329202) |
| コメント日時 | `2020-02-27T14:31:00Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
あかん、再現できん。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#534 コメント](https://bitbucket.org/sk_0520/pe/issues/534#comment-56358301) |
| コメント日時 | `2020-02-29T12:48:09Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
再現できた。

`\\MAIN\Music` みたいな直接パスを指定すると諸々の問題が発生する。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#534 コメント](https://bitbucket.org/sk_0520/pe/issues/534#comment-56361296) |
| コメント日時 | `2020-02-29T21:48:12Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #534


→ 《cset a5d5c96f6a86》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#534 コメント](https://bitbucket.org/sk_0520/pe/issues/534#comment-56362038) |
| コメント日時 | `2020-03-01T01:02:58Z` |
| コメントユーザー | `sk_0520` |
