### ISSUE TITLE
<Bitbucket:535> RDP接続で落ちる

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#535]
おそらくDPIやら解像度の問題なはず。

ログをもらった。

‌

```
2020-02-27 15:03:26.823|ERROR|  5492|<1>| 1, Object reference not set to an instance of an object. System.NullReferenceException: Object reference not set to an instance of an object.
   at ContentTypeTextNet.Pe.Main.ViewModels.Note.NoteViewModel.GetColorPair()
   at ContentTypeTextNet.Pe.Main.ViewModels.Note.NoteViewModel.ApplyCaption()
   at ContentTypeTextNet.Pe.Main.ViewModels.Note.NoteViewModel.<ApplyTheme>b__222_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#535](https://bitbucket.org/sk_0520/pe/issues/535) |
| 起票日時 | `2020-02-27T16:16:09Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #535


→ 《cset 430861596a61》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#535 コメント](https://bitbucket.org/sk_0520/pe/issues/535#comment-56358199) |
| コメント日時 | `2020-02-29T11:56:23Z` |
| コメントユーザー | `sk_0520` |
