### ISSUE TITLE
<Bitbucket:564> RDP 復帰後に落ちることがある

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#564]
ろぐもろた。

‌

```
2020-03-05 16:02:27.616|TRACE| 27123|<1>| [MSG WND] hwnd = 198462, msg = 537(WM_DEVICECHANGE), wParam = 7, lParam = 0  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.MessageWindowProc(0) | ApplicationManager | [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)]
2020-03-05 16:02:27.616|INFO | 27124|<1>| デバイス状態検知: DBT_DEVNODES_CHANGED  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CatchDeviceChanged(0) | ApplicationManager | [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [Void CatchDeviceChanged(ContentTypeTextNet.Pe.Main.Models.Data.DeviceChangedData)]
2020-03-05 16:02:27.616|INFO | 27125|<1>| ディスプレイ数変更検知: WindowsAPI = 2, Toolbar = 1  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CatchDeviceChanged(0) | ApplicationManager | [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [Void CatchDeviceChanged(ContentTypeTextNet.Pe.Main.Models.Data.DeviceChangedData)]
2020-03-05 16:02:27.679|ERROR| 27126|<1>| 1, Window が閉じている場合、Visibility を Visible に設定したり、Show、ShowDialog、Close、および WindowInteropHelper.EnsureHandle を呼び出したりすることはできません。 System.InvalidOperationException: Window が閉じている場合、Visibility を Visible に設定したり、Show、ShowDialog、Close、および WindowInteropHelper.EnsureHandle を呼び出したりすることはできません。
   at System.Windows.Window.VerifyNotClosing()
   at System.Windows.Window.InternalClose(Boolean shutdown, Boolean ignoreCancel)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CloseViewsCore(WindowKind windowKind)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CloseNoteViews()
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CloseViews()
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CatchDeviceChanged(DeviceChangedData deviceChangedData)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.MessageWindowProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#564](https://bitbucket.org/sk_0520/pe/issues/564) |
| 起票日時 | `2020-03-05T16:11:17Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #564


→ 《cset 3f959aa37dc4》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#564 コメント](https://bitbucket.org/sk_0520/pe/issues/564#comment-56420256) |
| コメント日時 | `2020-03-05T21:03:07Z` |
| コメントユーザー | `sk_0520` |
