### ISSUE TITLE
<Bitbucket:587> 非実行可能アイテムを指定して実行で標準入出力を受け取ると死ぬ

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#587]
あかんねー。

```
2020-03-16 14:35:13.646|ERROR|  4469|<1>| アクセスが拒否されました。 System.ComponentModel.Win32Exception (5): アクセスが拒否されました。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at ContentTypeTextNet.Pe.Main.Models.Launcher.LauncherExecutor.ExecuteFilePath(LauncherItemKind kind, ILauncherExecutePathParameter pathParameter, ILauncherExecuteCustomParameter customParameter, IEnumerable`1 environmentVariableItems, IScreen screen)
   at ContentTypeTextNet.Pe.Main.Models.Launcher.LauncherExecutor.Execute(LauncherItemKind kind, ILauncherExecutePathParameter pathParameter, ILauncherExecuteCustomParameter customParameter, IEnumerable`1 environmentVariableItems, IScreen screen)
   at ContentTypeTextNet.Pe.Main.Models.Element.ExtendsExecute.ExtendsExecuteElement.Execute(LauncherFileData fileData, IReadOnlyList`1 environmentVariables, IScreen screen) | ContentTypeTextNet.Pe.Main.Models.Element.ExtendsExecute.ExtendsExecuteElement.Execute(0) | LauncherExtendsExecuteElement | [Void Execute()] => [ContentTypeTextNet.Pe.Main.Models.Launcher.ILauncherExecuteResult Execute(ContentTypeTextNet.Pe.Main.Models.Data.LauncherFileData, System.Collections.Generic.IReadOnlyList`1[ContentTypeTextNet.Pe.Main.Models.Data.LauncherEnvironmentVariableData], ContentTypeTextNet.Pe.Bridge.Models.Data.IScreen)] => [ContentTypeTextNet.Pe.Main.Models.Launcher.ILauncherExecuteResult Execute(ContentTypeTextNet.Pe.Main.Models.Data.LauncherFileData, System.Collections.Generic.IReadOnlyList`1[ContentTypeTextNet.Pe.Main.Models.Data.LauncherEnvironmentVariableData], ContentTypeTextNet.Pe.Bridge.Models.Data.IScreen)]
2020-03-16 14:35:13.646|DEBUG|  4470|<1>| ウィンドウ破棄前: ContentTypeTextNet.Pe.Main.Views.ExtendsExecute.ExtendsExecuteWindow  | ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.Window_Closing(0) | WindowManager | [Boolean WmClose()] => [Void OnClosing(System.ComponentModel.CancelEventArgs)] => [Void Window_Closing(System.Object, System.ComponentModel.CancelEventArgs)]
2020-03-16 14:35:13.660|DEBUG|  4471|<1>| ウィンドウ破棄: ContentTypeTextNet.Pe.Main.Views.ExtendsExecute.ExtendsExecuteWindow  | ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.Window_Closed(0) | WindowManager | [Boolean WmDestroy()] => [Void OnClosed(System.EventArgs)] => [Void Window_Closed(System.Object, System.EventArgs)]
2020-03-16 14:35:13.723|DEBUG|  4472|<1>| ウィンドウハンドル生成: ContentTypeTextNet.Pe.Main.Views.StandardInputOutput.StandardInputOutputWindow  | ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.Window_SourceInitialized(0) | WindowManager | [Void CreateSourceWindow(Boolean)] => [Void OnSourceInitialized(System.EventArgs)] => [Void Window_SourceInitialized(System.Object, System.EventArgs)]
2020-03-16 14:35:13.735|DEBUG|  4473|<1>| ウィンドウ生成完了: ContentTypeTextNet.Pe.Main.Views.StandardInputOutput.StandardInputOutputWindow  | ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.Window_Loaded(0) | WindowManager | [Void RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)] => [Void InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)] => [Void Window_Loaded(System.Object, System.Windows.RoutedEventArgs)]
2020-03-16 14:35:17.832|TRACE|  4474|<1>| [MSG WND] hwnd = 4983258, msg = 28(28), wParam = 0, lParam = 25352  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.MessageWindowProc(0) | ApplicationManager | [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)]
2020-03-16 14:35:17.907|TRACE|  4475|<1>| [MSG WND] hwnd = 4983258, msg = 28(28), wParam = 1, lParam = 25352  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.MessageWindowProc(0) | ApplicationManager | [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)]
2020-03-16 14:35:19.990|ERROR|  4476|<1>| No process is associated with this object. System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at ContentTypeTextNet.Pe.Main.Models.Element.StandardInputOutput.StandardInputOutputElement.Kill()
   at ContentTypeTextNet.Pe.Main.ViewModels.StandardInputOutput.StandardInputOutputViewModel.<get_KillOutputCommand>b__55_1() | ContentTypeTextNet.Pe.Main.ViewModels.StandardInputOutput.StandardInputOutputViewModel.<get_KillOutputCommand>b__55_1(0) | StandardInputOutputViewModel | [Void OnClick()] => [Void CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)] => [Void <get_KillOutputCommand>b__55_1()]
2020-03-16 14:35:23.030|DEBUG|  4477|<1>| ウィンドウ破棄前(ユーザー操作): ContentTypeTextNet.Pe.Main.Views.StandardInputOutput.StandardInputOutputWindow, 000000000029174a  | ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.WndProc(0) | WindowManager | [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)]
2020-03-16 14:35:23.030|ERROR|  4478|<1>| 1, No process is associated with this object. System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at ContentTypeTextNet.Pe.Main.Models.Element.StandardInputOutput.StandardInputOutputElement.ReceiveViewUserClosing()
   at ContentTypeTextNet.Pe.Main.ViewModels.StandardInputOutput.StandardInputOutputViewModel.ReceiveViewUserClosing(CancelEventArgs e)
   at ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

---

```
Software: Pe
Version: 0.91.000-f5f4cbee87a753353e92f19a6f0ba26353b6d614
BuildType: Release
Process: 64
Platform: 64
OS: Microsoft Windows NT 10.0.18363.0
CLR: .NET Core 3.1.1
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#587](https://bitbucket.org/sk_0520/pe/issues/587) |
| 起票日時 | `2020-03-16T14:40:40Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #587


→ 《cset 52aa2db9d897》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#587 コメント](https://bitbucket.org/sk_0520/pe/issues/587#comment-56705659) |
| コメント日時 | `2020-03-29T18:23:19Z` |
| コメントユーザー | `sk_0520` |
