### ISSUE TITLE
<Bitbucket:588> ディスプレイ設定変更後に強制終了する時がある

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#588]
原因は知らん。

‌

```
2020-03-19 12:59:29.962|TRACE| 14535|<1>| [MSG WND] hwnd = 132106, msg = 49902(49902), wParam = 80, lParam = 0  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.MessageWindowProc(0) | ApplicationManager | [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)]
2020-03-19 12:59:29.996|INFO | 14536|<1>| ディスプレイ変更検知  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.SystemEvents_DisplaySettingsChanging(0) | ApplicationManager | [System.Object Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)] => [System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)] => [Void SystemEvents_DisplaySettingsChanging(System.Object, System.EventArgs)]
2020-03-19 12:59:30.056|INFO | 14572|<1>| initialize \\.\DISPLAY1:0,0,1920,1080, Primary: True  | ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement.InitializeImpl(0) | LauncherToolbarElement | [ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement CreateLauncherToolbarElement(ContentTypeTextNet.Pe.Bridge.Models.Data.IScreen, System.Collections.ObjectModel.ReadOnlyObservableCollection`1[ContentTypeTextNet.Pe.Main.Models.Element.LauncherGroup.LauncherGroupElement])] => [Void Initialize()] => [Void InitializeImpl()]
2020-03-19 12:59:30.056|TRACE| 14573|<1>| 参照アイテム生成/再使用: ContentTypeTextNet.Pe.Main.Models.Database.Dao.Domain.LauncherToolbarDomainDao.SelectAllScreenToolbars  | ContentTypeTextNet.Pe.Core.Models.ReferencePool`2.GetCore(0) | ReferencePool | [System.Collections.Generic.IEnumerable`1[ContentTypeTextNet.Pe.Main.Models.Data.LauncherToolbarsScreenData] SelectAllScreenToolbars()] => [TValue Get(TKey, System.Func`2[TKey,TValue])] => [TValue GetCore(TKey, System.TimeSpan, Boolean, System.Func`2[TKey,TValue])]
2020-03-19 12:59:30.056|INFO | 14574|<1>| toolbar id: 50482ade-0650-41ca-bc76-d81bda502e50  | ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement.LoadLauncherToolbar(0) | LauncherToolbarElement | [Void Initialize()] => [Void InitializeImpl()] => [Void LoadLauncherToolbar()]
2020-03-19 12:59:30.364|DEBUG| 14619|<8>| [PlatformThemeLoader] 実行  | ContentTypeTextNet.Pe.Core.Models.LazyAction.DoAction(0) | LazyAction | [Void MyTimerCallback(System.Object)] => [Void Timer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)] => [Void DoAction(Boolean)]
2020-03-19 12:59:30.364|TRACE| 14620|<8>| テーマ変更  | ContentTypeTextNet.Pe.Main.Models.Platform.PlatformThemeLoader.OnThemeChanged(0) | PlatformThemeLoader | [Void Timer_Elapsed(System.Object, System.Timers.ElapsedEventArgs)] => [Void DoAction(Boolean)] => [Void OnThemeChanged()]
2020-03-19 12:59:32.221|DEBUG| 14621|<1>| ウィンドウハンドル生成: ContentTypeTextNet.Pe.Main.Views.Note.NoteWindow  | ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.Window_SourceInitialized(0) | WindowManager | [Void OnSourceInitialized(System.EventArgs)] => [Void OnSourceInitialized(System.EventArgs)] => [Void Window_SourceInitialized(System.Object, System.EventArgs)]
2020-03-19 12:59:32.239|TRACE| 14622|<1>| [MSG WND] hwnd = 132106, msg = 28(28), wParam = 1, lParam = 0  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.MessageWindowProc(0) | ApplicationManager | [IntPtr WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr PublicHooksFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)] => [IntPtr MessageWindowProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)]
2020-03-19 12:59:32.251|ERROR| 14623|<1>| 1, Cannot access a disposed object.
Object name: 'GetLayout'. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'GetLayout'.
   at ContentTypeTextNet.Pe.Core.Models.NotifyPropertyBase.ThrowIfDisposed(String _callerMemberName)
   at ContentTypeTextNet.Pe.Main.Models.Element.Note.NoteElement.GetLayout()
   at ContentTypeTextNet.Pe.Main.ViewModels.Note.NoteViewModel.GetOrCreateLayout(NoteStartupPosition startupPosition)
   at ContentTypeTextNet.Pe.Main.ViewModels.Note.NoteViewModel.ReceiveViewInitialized(Window window)
   at ContentTypeTextNet.Pe.Main.Models.Manager.WindowManager.Window_SourceInitialized(Object sender, EventArgs e)
   at System.Windows.Window.OnSourceInitialized(EventArgs e)
   at ContentTypeTextNet.Pe.Main.Views.Note.NoteWindow.OnSourceInitialized(EventArgs e)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]


```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#588](https://bitbucket.org/sk_0520/pe/issues/588) |
| 起票日時 | `2020-03-20T12:27:12Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #588


→ 《cset 8ad089ea8629》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#588 コメント](https://bitbucket.org/sk_0520/pe/issues/588#comment-56590876) |
| コメント日時 | `2020-03-20T15:26:22Z` |
| コメントユーザー | `sk_0520` |
