### ISSUE TITLE
<Bitbucket:656> クラッシュレポートより: OutOfMemoryException でてる？

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#656]
`0.98.000`, `0.98.001` でそれぞれでてるっぽい？

なんか直近ログが出てないんよなぁ。。。それすら作れない状態なん？

‌

```
System.OutOfMemoryException: Insufficient memory to continue the execution 
of the program.
    at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
    at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean 
enableRenderTarget, Nullable`1 channelSet)
    at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
    at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, 
IntPtr wparam, IntPtr lparam)
    at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr 
hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, 
IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, 
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#656](https://bitbucket.org/sk_0520/pe/issues/656) |
| 起票日時 | `2020-06-30T23:28:48Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
とりま #657 に委譲して解決すれば閉じる。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#656 コメント](https://bitbucket.org/sk_0520/pe/issues/656#comment-58004933) |
| コメント日時 | `2020-06-30T23:38:26Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
わからん、再現レポートもない！
