### ISSUE TITLE
<Bitbucket:677> リリース物がないのにリリースノートを出そうとして死ぬ？

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#677]
わきゃらん。

```
2020-07-31 20:15:35.652|INFO |  1695|<17>| アップデート排他制御中  | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.ExecuteUpdateAsync(0) | ApplicationManager | [Void ExecutionContextCallback(System.Object)] => [Void MoveNext()] => [System.Threading.Tasks.Task ExecuteUpdateAsync(ContentTypeTextNet.Pe.Main.Models.Data.UpdateCheckKind)]
2020-07-31 20:15:35.668|ERROR|  1696|<1>| 1, ContentTypeTextNet.Pe.Main.Models.Element.ReleaseNote.ReleaseNoteElement: create error  ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiException: ContentTypeTextNet.Pe.Main.Models.Element.ReleaseNote.ReleaseNoteElement: create error 
   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiContainer.NewCore(Type type, String name, IEnumerable`1 manualParameters, Boolean useFactoryCache)
   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiContainer.New[TObject](IEnumerable`1 manualParameters)
   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.IDiContainerExtensions.Build[TObject](IDiContainer this, Object manualParameter, Object[] manualParameters)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.<>c__DisplayClass189_0.<ShowUpdateReleaseNote>g__Show|0()
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.<>c__DisplayClass189_0.<ShowUpdateReleaseNote>b__2()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) | ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(0) | App | [Boolean CatchExceptionStatic(System.Object, System.Exception)] => [Boolean CatchException(System.Exception)] => [Void Application_DispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)]
```

---

```
Software: Pe
Version: 0.99.013-be0ce0d1eb6495d9fd8a31d546145099089a8057
BuildType: Release
Process: 64
Platform: 64
OS: Microsoft Windows NT 10.0.19041.0
CLR: .NET Core 3.1.5
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#677](https://bitbucket.org/sk_0520/pe/issues/677) |
| 起票日時 | `2020-07-31T20:18:01Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
でるわぁ。。。

‌

```
		{
			"caller_class_name": "ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager",
			"caller_member_name": "ExecuteUpdateAsync",
			"caller_file_path": "",
			"caller_line_number": 0,
			"exception_string": "",
			"logger_name": "ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager",
			"formatted_message": "アップデート排他制御中",
			"parameters": [
				"アップデート排他制御中"
			],
			"message": "アップデート排他制御中",
			"level": "information",
			"stack_trace": [
				"   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.DelayCheckUpdateAsync()",
				"   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)",
				"   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)",
				"   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)",
				"   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()",
				"   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)",
				"   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)",
				"   at System.Threading.Tasks.Task.FinishContinuations()",
				"   at System.Threading.Tasks.Task.TrySetResult()",
				"   at System.Threading.Tasks.Task.DelayPromise.CompleteTimedOut()",
				"   at System.Threading.Tasks.Task.DelayPromise.<>c.<.ctor>b__1_0(Object state)",
				"   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)",
				"   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)",
				"   at System.Threading.TimerQueue.FireNextTimers()"
			],
			"sequence_id": 287,
			"timestamp": "2020-09-12T10:24:11.8272991Z"
		},
		{
			"caller_class_name": "ContentTypeTextNet.Pe.Main.App",
			"caller_member_name": "Application_DispatcherUnhandledException",
			"caller_file_path": "",
			"caller_line_number": 0,
			"exception_string": "ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiException: ContentTypeTextNet.Pe.Main.Models.Element.ReleaseNote.ReleaseNoteElement: create error \r\n   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiContainer.NewCore(Type type, String name, IEnumerable`1 manualParameters, Boolean useFactoryCache)\r\n   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiContainer.New(Type type, IEnumerable`1 manualParameters)\r\n   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.DiContainer.New[TObject](IEnumerable`1 manualParameters)\r\n   at ContentTypeTextNet.Pe.Core.Models.DependencyInjection.IDiContainerExtensions.Build[TObject](IDiContainer this, Object manualParameter, Object[] manualParameters)\r\n   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.<>c__DisplayClass192_0.<ShowUpdateReleaseNote>g__Show|0()\r\n   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.<>c__DisplayClass192_0.<ShowUpdateReleaseNote>b__2()\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)",
			"logger_name": "ContentTypeTextNet.Pe.Main.App",
			"formatted_message": "1, ContentTypeTextNet.Pe.Main.Models.Element.ReleaseNote.ReleaseNoteElement: create error ",
			"parameters": [
				"1",
				"ContentTypeTextNet.Pe.Main.Models.Element.ReleaseNote.ReleaseNoteElement: create error "
			],
			"message": "{0}, {1}",
			"level": "error",
			"stack_trace": [
				"   at ContentTypeTextNet.Pe.Main.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e)",
				"   at System.Windows.Threading.Dispatcher.CatchException(Exception e)",
				"   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)",
				"   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)",
				"   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)",
				"   at System.Windows.Threading.DispatcherOperation.InvokeImpl()",
				"   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)",
				"   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)",
				"   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)",
				"   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)",
				"   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)",
				"   at System.Windows.Threading.DispatcherOperation.Invoke()",
				"   at System.Windows.Threading.Dispatcher.ProcessQueue()",
				"   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)",
				"   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)",
				"   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)",
				"   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)",
				"   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)",
				"   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)",
				"   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)",
				"   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)",
				"   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)",
				"   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)",
				"   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)",
				"   at System.Windows.Threading.Dispatcher.Run()",
				"   at System.Windows.Application.RunDispatcher(Object ignore)",
				"   at System.Windows.Application.RunInternal(Window window)",
				"   at System.Windows.Application.Run()",
				"   at ContentTypeTextNet.Pe.Main.App.Main()"
			],
			"sequence_id": 288,
			"timestamp": "2020-09-12T10:24:11.8272991Z"
		},
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#677 コメント](https://bitbucket.org/sk_0520/pe/issues/677#comment-58763693) |
| コメント日時 | `2020-09-12T20:21:30Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
再現方法がないのなぁ。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#677 コメント](https://bitbucket.org/sk_0520/pe/issues/677#comment-58955221) |
| コメント日時 | `2020-10-04T18:35:58Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
resolved #677


→ 《cset eed5767ba5e8》

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#677 コメント](https://bitbucket.org/sk_0520/pe/issues/677#comment-58955272) |
| コメント日時 | `2020-10-04T19:02:32Z` |
| コメントユーザー | `sk_0520` |
