### ISSUE TITLE
<Bitbucket:720> [Pe-CrashReport] プログラム自動取り込みで NullReferenceException が発生している？

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#720]
```
タイムスタンプ: 2020-12-13T02:41:39.000Z
報告者アドレス:
-----例外情報-----
System.NullReferenceException: Object reference not set to an instance of 
an object.
    at ContentTypeTextNet.Pe.Core.ViewModels.RequestSender.OnRaised(RequestParameter requestParameter, Action`1 callback)
    at ContentTypeTextNet.Pe.Core.ViewModels.RequestSender.Send(RequestParameter requestParameter, Action`1 callback)
    at ContentTypeTextNet.Pe.Core.ViewModels.RequestSender.Send(RequestParameter requestParameter)
    at ContentTypeTextNet.Pe.Core.ViewModels.RequestSender.Send()
    at ContentTypeTextNet.Pe.Main.ViewModels.Startup.ImportProgramsViewModel.<get_ImportCommand>b__14_1()
    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

えぇ、これまじでぇ・・・。

と、思ったけどこれ古ない？

[https://drive.google.com/file/d/1EOS4PwDVtGcwRw4gmYqgmRxg8Vm\_0roc/view?usp=sharing](https://drive.google.com/file/d/1EOS4PwDVtGcwRw4gmYqgmRxg8Vm_0roc/view?usp=sharing)

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#720](https://bitbucket.org/sk_0520/pe/issues/720) |
| 起票日時 | `2020-12-13T21:47:45Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
ふるいでしょこれ。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#720 コメント](https://bitbucket.org/sk_0520/pe/issues/720#comment-60528123) |
| コメント日時 | `2021-05-16T22:57:07Z` |
| コメントユーザー | `sk_0520` |
