### ISSUE TITLE
<Bitbucket:776> 特定のプラグインアンインストール時に外部キー制約で失敗する

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#776]
まじかこれ。

```
2021-09-17 20:04:29.867|ERROR|   155|<1>| constraint failed
FOREIGN KEY constraint failed code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
FOREIGN KEY constraint failed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2813
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseAccessor.Execute(String statement, Object parameter, IDatabaseTransaction transaction) in .\Pe.Core\Models\Database\DatabaseAccessor.cs:line 531
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseTransaction.Execute(String statement, Object parameter) in .\Pe.Core\Models\Database\DatabaseTransaction.cs:line 138
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseBarrierTransaction.Execute(String statement, Object parameter) in .\Pe.Core\Models\Database\DatabaseBarrier.cs:line 40
   at ContentTypeTextNet.Pe.Main.Models.Database.Dao.Entity.PluginsEntityDao.DeletePlugin(Guid pluginId) in .\Pe.Main\Models\Database\Dao\Entity\PluginsEntityDao.cs:line 160
   at ContentTypeTextNet.Pe.Main.Models.Plugin.PluginUninstaller.UninstallPersistent(IPluginIdentifiers pluginIdentifiers) in .\Pe.Main\Models\Plugin\PluginUninstaller.cs:line 122
   at ContentTypeTextNet.Pe.Main.Models.Plugin.PluginUninstaller.Uninstall(IPluginIdentifiers pluginIdentifiers) in .\Pe.Main\Models\Plugin\PluginUninstaller.cs:line 129
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.LoadPlugins() in .\Pe.Main\Models\Manager\ApplicationManager.cs:line 657 | ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.LoadPlugins(657) | ApplicationManager | [Void OnStartup(System.Windows.StartupEventArgs)] => [Boolean Startup(ContentTypeTextNet.Pe.Main.App, System.Windows.StartupEventArgs)] => [Void LoadPlugins()]
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#776](https://bitbucket.org/sk_0520/pe/issues/776) |
| 起票日時 | `2021-09-17T20:19:06Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
#735 対応中しか発生しないので課題としては不要。
#735 内で対応する。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#776 コメント](https://bitbucket.org/sk_0520/pe/issues/776#comment-61159009) |
| コメント日時 | `2021-09-18T11:22:09Z` |
| コメントユーザー | `sk_0520` |
