### ISSUE TITLE
<Bitbucket:814> ランチャーツールバーの「自動的に隠す」切り替えで死ぬ？

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#814]
---

```
Software: Pe
Version: 0.99.176-71e361fcd9ba04d996e8c7d0635587d7486c0cc1
BuildType: Release
Process: 64
Platform: 64
OS: Microsoft Windows NT 10.0.19044.0
CLR: .NET 6.0.8
```

いやもうつらい。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元課題 | [#814](https://bitbucket.org/sk_0520/pe/issues/814) |
| 起票日時 | `2022-09-19T23:30:29Z` |
| 起票者 | `sk_0520` |

**Comment by sk-0520** [comment]
タイミングわっかんねぇなぁこれ。

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#814 コメント](https://bitbucket.org/sk_0520/pe/issues/814#comment-64111435) |
| コメント日時 | `2022-09-19T23:31:56Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
更新処理で更新不要条件がある場合はいらんなこれ。

```
UpdatIsAutoHide
ContentTypeTextNet.Pe.Core.Models.Database.DatabaseContextException
  HResult=0x80131500
  Message=update -> 0
  Source=Pe.Core
  スタック トレース:
   at ContentTypeTextNet.Pe.Core.Models.Database.IDatabaseWriterExtensions.UpdateByKey(IDatabaseWriter writer, String statement, Object parameter) in .\Pe.Core\Models\Database\DatabaseContextExtensions.cs:line 123
   at ContentTypeTextNet.Pe.Main.Models.Database.Dao.Entity.LauncherToolbarsEntityDao.UpdatIsAutoHide(LauncherToolbarId launcherToolbarId, Boolean isAutoHide, IDatabaseCommonStatus commonStatus) in .\Pe.Main\Models\Database\Dao\Entity\LauncherToolbarsEntityDao.cs:line 175
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement.<ChangeAutoHideDelaySave>b__120_0(IDatabaseTransaction c) in .\Pe.Main\Models\Element\LauncherToolbar\LauncherToolbarElement.cs:line 402
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseLazyWriter.FlushCore(LazyStockItem[] stockItems) in .\Pe.Core\Models\Database\DatabaseLazyWriter.cs:line 166
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseLazyWriter.Flush(Boolean disposing) in .\Pe.Core\Models\Database\DatabaseLazyWriter.cs:line 248
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseLazyWriter.Flush() in .\Pe.Core\Models\Database\DatabaseLazyWriter.cs:line 254
   at ContentTypeTextNet.Pe.Core.Models.Database.DatabaseLazyWriter.LazyCallback(Object state) in .\Pe.Core\Models\Database\DatabaseLazyWriter.cs:line 159
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__27_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

‌

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#814 コメント](https://bitbucket.org/sk_0520/pe/issues/814#comment-64113657) |
| コメント日時 | `2022-09-20T13:59:58Z` |
| コメントユーザー | `sk_0520` |

**Comment by sk-0520** [comment]
6a165d45f7d9ec2b5a126c4d39a8d313edb921b0

---------------------

### BitBucket から移植

| 項目 | 内容 |
|:-:|:--|
| 元コメント | [#814 コメント](https://bitbucket.org/sk_0520/pe/issues/814#comment-64115249) |
| コメント日時 | `2022-09-20T20:04:29Z` |
| コメントユーザー | `sk_0520` |
