### ISSUE TITLE
クラッシュレポート: 9

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#886]
```
2023-07-05 16:36:34
0.99.199
------------------
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ContentTypeTextNet.Pe.Standard.Base.WrapStreamBase.get_CanSeek()
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at ContentTypeTextNet.Pe.Standard.Base.Initializer.Dispose(Boolean disposing)
   at ContentTypeTextNet.Pe.Main.Models.Logic.IconImageLoaderBase.LoadFromStream(Stream stream)
   at ContentTypeTextNet.Pe.Main.Models.Logic.IconImageLoaderBase.<>c.b__17_1(MemoryReleaseStream s)
   at ContentTypeTextNet.Pe.Core.Models.DispatcherWrapper.<>c__20`2.b__20_0(WaitParameter`2 waitParameter)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

んんん～～～？ ログがないとさすがに分からんかなぁ、対象ファイルさえあればなんとかなる？

あと別にクラッシュができではない。。。

**Comment by sk-0520** [comment]
* シークできない: 負数BMP？
* そもそもが画像としておかしい？
* 落とすべきでない？

**Comment by sk-0520** [comment]
メールにて連携済み、情報あればさらに追記・対応予定。

**Comment by sk-0520** [comment]
わからん。
