### ISSUE TITLE
[クラッシュレポート: 23] LauncherItems.Code

### ISSUE THREAD

**Issue by sk-0520** [sk-0520/Pe#951]
https://peserver.site/management/crash-report/23

`LauncherItems.Code` ってないはずなのになんでなんだ、動的生成してたっけ。

バージョン: 0.99.230 古いな、わからん。

```
System.AggregateException: One or more errors occurred. (SQL logic error
no such column: LauncherItems.Code)
 ---> code = Error (1), message = System.Data.SQLite.SQLiteException (0x87AF001F): SQL logic error
no such column: LauncherItems.Code
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, SQLiteCommand command, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1156
   at Dapper.SqlMapper.QueryRowImpl[T](IDbConnection cnn, Row row, CommandDefinition& command, Type effectiveType) in /_/Dapper/SqlMapper.cs:line 1277
   at Dapper.SqlMapper.QuerySingle[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 878
   at ContentTypeTextNet.Pe.Standard.Database.DatabaseAccessor.QuerySingle[T](IDatabaseTransaction transaction, String statement, Object parameter)
   at ContentTypeTextNet.Pe.Standard.Database.DatabaseTransaction.QuerySingle[T](String statement, Object parameter)
   at ContentTypeTextNet.Pe.Standard.Database.FE99800234FBD148577C6C63832D7580285C7A12828D5681D9B55F573FBC634F9__DatabaseBarrierTransaction.QuerySingle[T](String statement, Object parameter)
   at ContentTypeTextNet.Pe.Main.Models.Database.Dao.Entity.LauncherItemsEntityDao.SelectLauncherItem(LauncherItemId launcherItemId)
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherItem.LauncherItemElement.LoadLauncherItem()
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherItem.LauncherItemElement.InitializeCoreAsync()
   at ContentTypeTextNet.Pe.Main.Models.Element.ElementBase.InitializeAsync()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.OrderManagerImpl.b__11_0(LauncherItemId launcherItemIdKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.OrderManagerImpl.GetOrCreateLauncherItemElement(LauncherItemId launcherItemId)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.GetOrCreateLauncherItemElement(LauncherItemId launcherItemId)
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement.GetLauncherItems()
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement.LoadLauncherItems()
   at ContentTypeTextNet.Pe.Main.Models.Element.LauncherToolbar.LauncherToolbarElement.InitializeCoreAsync()
   at ContentTypeTextNet.Pe.Main.Models.Element.ElementBase.InitializeAsync()
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.OrderManagerImpl.CreateLauncherToolbarElementAsync(IScreen dockScreen, ReadOnlyObservableCollection`1 launcherGroups)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.CreateLauncherToolbarElementsAsync(ReadOnlyObservableCollection`1 launcherGroups)
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.ExecuteElementsAsync()
   at ContentTypeTextNet.Pe.Main.Models.Manager.ApplicationManager.ExecuteAsync()
   at ContentTypeTextNet.Pe.Main.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by sk-0520** [comment]
メールアドレス提供してくれてたのでユーザー確認中。

**Comment by sk-0520** [comment]
あと `FE99800234FBD148577C6C63832D7580285C7A12828D5681D9B55F573FBC634F9__DatabaseBarrierTransaction` これが分からない。

**Comment by sk-0520** [comment]
* 0.99.230 で存在するカラムがない
* 最新版対応してもらうとマイグレーション 0.99.235 で落ちる

もう全然わからな過ぎて何もわからない。

**Comment by sk-0520** [comment]
削除対応で実行可能になった模様。

削除対応なので根治ではない。
